# Generated by Django 2.1.4 on 2018-12-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=100)),
                ('ls', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('trader', models.CharField(max_length=1000)),
                ('order_date', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('cash', models.FloatField(default=1000000)),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
    ]
